export type City = {
  name: string;
  country: string;
  continentSlug: string;
  rank: number;
};

export const cities: City[] = [
  {
    rank: 1,
    name: 'Hong Kong',
    country: 'China',
    continentSlug: 'asia',
  },
  {
    rank: 2,
    name: 'Bangkok',
    country: 'Thailand',
    continentSlug: 'asia',
  },
  {
    rank: 3,
    name: 'London',
    country: 'United Kingdom',
    continentSlug: 'europa',
  },
  {
    rank: 4,
    name: 'Macau',
    country: 'China',
    continentSlug: 'asia',
  },
  {
    rank: 5,
    name: 'Singapore',
    country: 'Singapore',
    continentSlug: 'asia',
  },
  {
    rank: 6,
    name: 'Paris',
    country: 'France',
    continentSlug: 'europa',
  },
  {
    rank: 7,
    name: 'Dubai',
    country: 'UAE',
    continentSlug: 'asia',
  },
  {
    rank: 8,
    name: 'New York City',
    country: 'US',
    continentSlug: 'america-do-norte',
  },
  {
    rank: 9,
    name: 'Kuala Lumpur',
    country: 'Malaysia',
    continentSlug: 'asia',
  },
  {
    rank: 10,
    name: 'Istanbul',
    country: 'Turkey',
    continentSlug: 'europa',
  },
  {
    rank: 11,
    name: 'Delhi',
    country: 'India',
    continentSlug: 'asia',
  },
  {
    rank: 12,
    name: 'Antalya',
    country: 'Turkey',
    continentSlug: 'europa',
  },
  {
    rank: 13,
    name: 'Shenzhen',
    country: 'China',
    continentSlug: 'asia',
  },
  {
    rank: 14,
    name: 'Mumbai',
    country: 'India',
    continentSlug: 'asia',
  },
  {
    rank: 15,
    name: 'Phuket',
    country: 'Thailand',
    continentSlug: 'asia',
  },
  {
    rank: 16,
    name: 'Rome',
    country: 'Italy',
    continentSlug: 'europa',
  },
  {
    rank: 17,
    name: 'Tokyo',
    country: 'Japan',
    continentSlug: 'asia',
  },
  {
    rank: 18,
    name: 'Pattaya',
    country: 'Thailand',
    continentSlug: 'asia',
  },
  {
    rank: 19,
    name: 'Taipei',
    country: 'Taiwan',
    continentSlug: 'asia',
  },
  {
    rank: 20,
    name: 'Mecca',
    country: 'Saudi Arabia',
    continentSlug: 'asia',
  },
  {
    rank: 21,
    name: 'Guangzhou',
    country: 'China',
    continentSlug: 'asia',
  },
  {
    rank: 22,
    name: 'Prague',
    country: 'Czechia',
    continentSlug: 'europa',
  },
  {
    rank: 23,
    name: 'Medina',
    country: 'Saudi Arabia',
    continentSlug: 'asia',
  },
  {
    rank: 24,
    name: 'Seoul',
    country: 'South Korea',
    continentSlug: 'asia',
  },
  {
    rank: 25,
    name: 'Amsterdam',
    country: 'Netherlands',
    continentSlug: 'europa',
  },
  {
    rank: 26,
    name: 'Agra',
    country: 'India',
    continentSlug: 'asia',
  },
  {
    rank: 27,
    name: 'Miami',
    country: 'US',
    continentSlug: 'america-do-norte',
  },
  {
    rank: 28,
    name: 'Osaka',
    country: 'Japan',
    continentSlug: 'asia',
  },
  {
    rank: 29,
    name: 'Los Angeles',
    country: 'US',
    continentSlug: 'america-do-norte',
  },
  {
    rank: 30,
    name: 'Shanghai',
    country: 'China',
    continentSlug: 'asia',
  },
  {
    rank: 31,
    name: 'Ho Chi Minh City',
    country: 'Vietnam',
    continentSlug: 'asia',
  },
  {
    rank: 32,
    name: 'Denpasar',
    country: 'Indonesia',
    continentSlug: 'asia',
  },
  {
    rank: 33,
    name: 'Barcelona',
    country: 'Spain',
    continentSlug: 'europa',
  },
  {
    rank: 34,
    name: 'Las Vegas',
    country: 'US',
    continentSlug: 'america-do-norte',
  },
  {
    rank: 35,
    name: 'Milan',
    country: 'Italy',
    continentSlug: 'europa',
  },
  {
    rank: 36,
    name: 'Chennai',
    country: 'India',
    continentSlug: 'asia',
  },
  {
    rank: 37,
    name: 'Vienna',
    country: 'Austria',
    continentSlug: 'oceania',
  },
  {
    rank: 38,
    name: 'Johor Bahru',
    country: 'Malaysia',
    continentSlug: 'asia',
  },
  {
    rank: 39,
    name: 'Jaipur',
    country: 'India',
    continentSlug: 'asia',
  },
  {
    rank: 40,
    name: 'Cancun',
    country: 'Mexico',
    continentSlug: 'america-do-norte',
  },
  {
    rank: 41,
    name: 'Berlin',
    country: 'Germany',
    continentSlug: 'europa',
  },
  {
    rank: 42,
    name: 'Cairo',
    country: 'Egypt',
    continentSlug: 'africa',
  },
  {
    rank: 43,
    name: 'Athens',
    country: 'Greece',
    continentSlug: 'europa',
  },
  {
    rank: 44,
    name: 'Orlando',
    country: 'US',
    continentSlug: 'america-do-norte',
  },
  {
    rank: 45,
    name: 'Moscow',
    country: 'Russia',
    continentSlug: 'europa',
  },
  {
    rank: 46,
    name: 'Venice',
    country: 'Italy',
    continentSlug: 'europa',
  },
  {
    rank: 47,
    name: 'Madrid',
    country: 'Spain',
    continentSlug: 'europa',
  },
  {
    rank: 48,
    name: 'Ha Long',
    country: 'Vietnam',
    continentSlug: 'asia',
  },
  {
    rank: 49,
    name: 'Riyadh',
    country: 'Saudi Arabia',
    continentSlug: 'asia',
  },
  {
    rank: 50,
    name: 'Dublin',
    country: 'Ireland',
    continentSlug: 'europa',
  },
  {
    rank: 51,
    name: 'Florence',
    country: 'Italy',
    continentSlug: 'europa',
  },
  {
    rank: 52,
    name: 'Ha Noi',
    country: 'Vietnam',
    continentSlug: 'asia',
  },
  {
    rank: 53,
    name: 'Toronto',
    country: 'Canada',
    continentSlug: 'america-do-norte',
  },
  {
    rank: 54,
    name: 'Johannesburg',
    country: 'South Africa',
    continentSlug: 'africa',
  },
  {
    rank: 55,
    name: 'Sydney',
    country: 'Australia',
    continentSlug: 'oceania',
  },
  {
    rank: 56,
    name: 'Munich',
    country: 'Germany',
    continentSlug: 'europa',
  },
  {
    rank: 57,
    name: 'Jakarta',
    country: 'Indonesia',
    continentSlug: 'asia',
  },
  {
    rank: 58,
    name: 'Beijing',
    country: 'China',
    continentSlug: 'asia',
  },
  {
    rank: 59,
    name: 'St. Petersburg',
    country: 'Russia',
    continentSlug: 'europa',
  },
  {
    rank: 60,
    name: 'Brussels',
    country: 'Belgium',
    continentSlug: 'europa',
  },
  {
    rank: 61,
    name: 'Jerusalem',
    country: 'Israel',
    continentSlug: 'asia',
  },
  {
    rank: 62,
    name: 'Budapest',
    country: 'Hungary',
    continentSlug: 'europa',
  },
  {
    rank: 63,
    name: 'Lisbon',
    country: 'Portugal',
    continentSlug: 'europa',
  },
  {
    rank: 64,
    name: 'Dammam',
    country: 'Saudi Arabia',
    continentSlug: 'asia',
  },
  {
    rank: 65,
    name: 'Penang Island',
    country: 'Malaysia',
    continentSlug: 'asia',
  },
  {
    rank: 66,
    name: 'Heraklion',
    country: 'Greece',
    continentSlug: 'europa',
  },
  {
    rank: 67,
    name: 'Kyoto',
    country: 'Japan',
    continentSlug: 'asia',
  },
  {
    rank: 68,
    name: 'Zhuhai',
    country: 'China',
    continentSlug: 'asia',
  },
  {
    rank: 69,
    name: 'Vancouver',
    country: 'Canada',
    continentSlug: 'america-do-norte',
  },
  {
    rank: 70,
    name: 'Chiang Mai',
    country: 'Thailand',
    continentSlug: 'asia',
  },
  {
    rank: 71,
    name: 'Copenhagen',
    country: 'Denmark',
    continentSlug: 'europa',
  },
  {
    rank: 72,
    name: 'San Francisco',
    country: 'US',
    continentSlug: 'america-do-norte',
  },
  {
    rank: 73,
    name: 'Melbourne',
    country: 'Australia',
    continentSlug: 'oceania',
  },
  {
    rank: 74,
    name: 'Krakow',
    country: 'Poland',
    continentSlug: 'asia',
  },
  {
    rank: 75,
    name: 'Marrakech',
    country: 'Morocco',
    continentSlug: 'africa',
  },
  {
    rank: 76,
    name: 'Kolkatta',
    country: 'India',
    continentSlug: 'asia',
  },
  {
    rank: 77,
    name: 'Cebu',
    country: 'Philippines',
    continentSlug: 'asia',
  },
  {
    rank: 78,
    name: 'Auckland',
    country: 'New Zealand',
    continentSlug: 'oceania',
  },
  {
    rank: 79,
    name: 'Tel Aviv',
    country: 'Israel',
    continentSlug: 'asia',
  },
  {
    rank: 80,
    name: 'Guilin',
    country: 'China',
    continentSlug: 'asia',
  },
  {
    rank: 81,
    name: 'Honolulu',
    country: 'US',
    continentSlug: 'america-do-norte',
  },
  {
    rank: 82,
    name: 'Hurgada',
    country: 'Egypt',
    continentSlug: 'africa',
  },
  {
    rank: 83,
    name: 'Warsaw',
    country: 'Poland',
    continentSlug: 'europa',
  },
  {
    rank: 84,
    name: 'Mugla',
    country: 'Turkey',
    continentSlug: 'europa',
  },
  {
    rank: 85,
    name: 'Buenos Aires City',
    country: 'Argentina',
    continentSlug: 'america-do-sul',
  },
  {
    rank: 86,
    name: 'Chiba',
    country: 'Japan',
    continentSlug: 'asia',
  },
  {
    rank: 87,
    name: 'Frankfurt',
    country: 'Germany',
    continentSlug: 'europa',
  },
  {
    rank: 88,
    name: 'Stockholm',
    country: 'Sweden',
    continentSlug: 'europa',
  },
  {
    rank: 89,
    name: 'Lima',
    country: 'Peru',
    continentSlug: 'america-do-sul',
  },
  {
    rank: 90,
    name: 'Da Nang',
    country: 'Vietnam',
    continentSlug: 'asia',
  },
  {
    rank: 91,
    name: 'Batam',
    country: 'Indonesia',
    continentSlug: 'asia',
  },
  {
    rank: 92,
    name: 'Nice',
    country: 'France',
    continentSlug: 'europa',
  },
  {
    rank: 93,
    name: 'Fukuoka',
    country: 'Japan',
    continentSlug: 'asia',
  },
  {
    rank: 94,
    name: 'Abu Dhabi',
    country: 'UAE',
    continentSlug: 'asia',
  },
  {
    rank: 95,
    name: 'Jeju',
    country: 'South Korea',
    continentSlug: 'asia',
  },
  {
    rank: 96,
    name: 'Porto',
    country: 'Portugal',
    continentSlug: 'europa',
  },
  {
    rank: 97,
    name: 'Rhodes',
    country: 'Greece',
    continentSlug: 'europa',
  },
  {
    rank: 98,
    name: 'Rio de Janeiro',
    country: 'Brazil',
    continentSlug: 'america-do-sul',
  },
  {
    rank: 99,
    name: 'Krabi',
    country: 'Thailand',
    continentSlug: 'asia',
  },
  {
    rank: 100,
    name: 'Bangalore',
    country: 'India',
    continentSlug: 'asia',
  },
];
